### PR TITLE
IdentityStore eager instantiation

### PR DESCRIPTION
**Pull request by ggam**
Proposal for https://javaee.groups.io/g/javaee-security-spec/topic/identitystore_authenticationmechanism/5622784?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,5622784

### CODE REVIEW

**Comment by arjantijms** [comment]
This may be difficult, as the scope is unknown (even though application scoped would be recommended). If the developer gives an identity store a request scope, it would obviously fail to initialise when the container attempts this during startup.

**Comment by ggam** [comment]
Well, we still have some options I think:
- Use an EJB to do the check (https://github.com/javaee/security-soteria/pull/144/files) as it will have the request scope enabled. Note that it doesn't impose a dependency on EJB as not available annotations are just ignored at runtime. It would just not enable request scope on implementations that don't support EJBs.
- Using CDI 2.0, manually activate the request scope. We are still not using it on Soteria, but this is a Java EE 8 spec and implementors are free to use it.
- Require only "application scoped" to be supported. I don't think this would be a problem at all. Identity stores should be stateless anyway and I personally don't see a reason to mark them @RequestScoped (myabe I'm missing something).

My personal preference is the third. And then again, deployment-time expressions could reference request scoped beans, which would also be a problem. But then again, I think the EJB trick+CDI 2.0 would be enough since anyway, nobody should be trying to use a request scoped bean on a deployment time expression. We support request time expressions for that precisely, and you can cache the result upon first execution.

**Comment by wmhopkins** [comment]
I'm not thrilled about the proposed language, as I think "eagerly" is imprecise and therefore doesn't help implementors know what's really required.

I do think it might be reasonable to require identity stores to be application scoped, unless there would be legitimate reasons to specify a different scope. On the other hand, we are a day away from our date to deliver FAB materials, so I'm reluctant to suggest a change of that nature that might impact TCK assertions.

**Comment by ggam** [comment]
> I'm not thrilled about the proposed language, as I think "eagerly" is imprecise and therefore doesn't help implementors know what's really required.

Well, you know my English is far from perfect :) I'm sure someone else could find a better term.

Anyway, this can again be done on the RI side for the moment and revisited for a future release. I understand this needs some more discussion than I expected.

> I do think it might be reasonable to require identity stores to be application scoped, unless there would be legitimate reasons to specify a different scope. On the other hand, we are a day away from our date to deliver FAB materials, so I'm reluctant to suggest a change of that nature that might impact TCK assertions.

The @ApplicationScoped restriction should not affect the TCK, as we are just specifying that implementations need to support it (which was already the case). But restricting the valid scopes now and expanding them on futures releases is easier than the opposite.

**Comment by ggam** [comment]
> I do think it might be reasonable to require identity stores to be application scoped

Just to clarify, I mean "requiring" support only for application scoped. Implementations would be free to support more scopes.

**Comment by wmhopkins** [comment]
@ggam - Actually, your English is very good -- my concern about "eagerly" is that it essentially means, "as soon as possible", which doesn't actually create any specific requirement. Does that mean during deployment? Before first use? Etc. Without being more specific, implementors won't know what they are required to do, and I don't think we are able, now, to specify anything more definite.

**Comment by ggam** [comment]
@wmhopkins I used the "eager" term as I was already familiar with it from http://docs.oracle.com/javaee/7/api/javax/faces/bean/ManagedBean.html and I think I've seen it somewhere else.

Tt's indeed a rather ambiguous term, but it was partially done on purpose. The important part of that sentence is that the deployment will fail if identity stores failed to be created, so its creation must be done during deployment. I personally don't really care wether that creation is done via a CDI extension or just manually injecting them all (as I did on Soteria). But its true that a spec must be clear. 

>  The container MUST instantiate __IdentityStore__s during deployment and fail it (the deployment) in case of error. 

Would probably be much more explicit.

**Comment by arjantijms** [comment]
Eagerly instantiate during deployment is always an issue I think since we allow user-defined scopes. These scopes don't really have to exclusively be the request- or application scope, but can be anything (scopes can be user-defined after all).

As I think Darran mentioned on the EG list once, in some cases the relation between the authentication mechanism and the identity store is quite intricate and not as clear cut as say in FORM. For those situations the user could build say an "OAuthScoped" scope, which would theoretically be active during the OAuth flow and if the user doesn't want sessions could be based on (encrypted) data in OAuth's state parameters.

Another example may be an authentication sequence modelled by a JSF flow and making use of the flow scope.

There's probably 1001 of such things we can't even anticipate now, but we can anticipate that instantiating them during deployment is by far not always possible.

**Comment by ggam** [comment]
Thanks again Arjan for the insight. It's clear that this is far more
complicated than I thought.

Leaving aside the spec text, a good starting point (for the RI) could be to
just instantiate built-in identity stores that we know can be done eagerly.
But again, that should wait until the spec and Soteria 1.0 have been
delivered.

**Pull request closed without merging**
